name: Spring Boot Docker Image CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, label-build-1]

    steps:
      # 소스 복사
      #- name: source copy
      #  run: git clone https://github.com/LargeSsun/kosa-devops-step2
      - uses: actions/checkout@v3
      
#      - name: Setup JDK17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'

      - name: Set gradlew's exec perm
        run: chmod +x gradlew

      - name: Test with gradle
        run: ./gradlew --info test

      - name: Make Spring boot's exec file
        run: ./gradlew bootJar

      - name: Make docker image
        run: docker build -t hyunhojang/devops_step2:v1.0 .

      - name: docker login
        #run: docker login -u hyunhojang -p${{secrets.DOCKER_PASSWORD}}
        uses: docker/login-action@v1
        with:
          username: hyunhojang
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: save docker image to hub
        run: docker push hyunhojang/devops_step2:v1.0

      - name: Upload setting files
        uses: actions/upload-artifact@v4
        with:
          name: setting-files
          path: |
            docker-compose_nginx.yml
            nginx/nginx.conf
        
  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, label-jhh-1]
    steps:
#      - uses: actions/checkout@v3
#        with:
#          sparse-checkout: |
#            docker-compose_nginx.yml
#            nginx/nginx.conf
#          sparse-checkout-cone-mode: false
#          clean: true

      - name: Download setting files
        uses: actions/download-artifact@v4
        with:
          name: setting-files
          path: .

      - name: docker login
        #run: docker login -u hyunhojang -p${{secrets.DOCKER_PASSWORD}}
        #plz plz
        uses: docker/login-action@v1
        with:
          username: hyunhojang
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: pull docker image
        run: docker pull hyunhojang/devops_step2:v1.0

      - name: run docker container
        run: docker compose -f docker-compose_nginx.yml up -d
      
      - name: check container status
        run: docker ps -a
      
      - name: cleanup old images
        run: docker image prune -f
        
      
